"""
Trade signal models — structured data types for trade ideas generated by Claude.
"""

from datetime import datetime
from enum import Enum

from pydantic import BaseModel, Field


class TradeAction(str, Enum):
    BUY = "buy"
    SELL = "sell"
    HOLD = "hold"
    BUY_CALL = "buy_call"
    BUY_PUT = "buy_put"
    SELL_CALL = "sell_call"
    SELL_PUT = "sell_put"


class Conviction(str, Enum):
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"


class TradeSignal(BaseModel):
    """A single trade recommendation from Claude's analysis."""

    symbol: str
    action: TradeAction
    conviction: Conviction
    target_price: float | None = None
    stop_loss_price: float | None = None
    position_size_pct: float = Field(
        description="Suggested position size as % of portfolio", ge=0, le=1
    )
    rationale: str = Field(default="", description="Claude's reasoning for this trade")
    time_horizon: str = Field(default="unspecified", description="Expected holding period, e.g. '3-5 days', '1-2 weeks'")
    risk_reward_ratio: float | None = Field(
        default=None, description="Estimated risk/reward ratio"
    )

    # Catalyst flag — for closing cycle entries that have a specific overnight catalyst
    is_catalyst_trade: bool = Field(
        default=False,
        description="True if this trade is driven by a specific catalyst (earnings, FDA, etc.). Required for closing cycle entries.",
    )
    catalyst: str | None = Field(
        default=None,
        description="The specific catalyst, e.g. 'AAPL earnings after close', 'FDA approval expected'. Required if is_catalyst_trade=true.",
    )

    # Options-specific fields
    strike_price: float | None = None
    expiration_date: str | None = None
    option_type: str | None = None  # "call" or "put"


class MarketAnalysis(BaseModel):
    """Claude's overall market assessment."""

    timestamp: datetime = Field(default_factory=datetime.now)
    market_regime: str = Field(description="bull, bear, sideways, volatile, etc.")
    regime_confidence: Conviction
    key_observations: list[str]
    sector_outlook: dict[str, str] = Field(
        default_factory=dict, description="Sector -> outlook mapping"
    )
    market_summary: str = Field(
        default="",
        description="2-3 sentence narrative of current market conditions, thought process, and reasoning for actions taken or not taken this cycle.",
    )
    trade_signals: list[TradeSignal] = Field(default_factory=list)
    positions_to_close: list[str] = Field(
        default_factory=list, description="Symbols to exit"
    )
    stop_adjustments: dict[str, float] = Field(
        default_factory=dict,
        description="Symbol -> new stop price. Adjusts existing stops on open positions.",
    )
    raw_analysis: str = Field(description="Full Claude response for logging")
